CC-1057: Refactor RDB Pesrsistence stages to use our RESP framework.
codecrafters-io/redis-tester pull request #141
Opened 2024-05-01 08:13 UTC by ryan-gang

2024-05-01 20:30 UTC, ryan-gang commented
This is the logs on Master currently. (Running make test on my local)
```
[stage-201] Running tests for Stage #1: RDB Config
[stage-201] $ ./spawn_redis_server.sh --dir /private/var/folders/5l/z5y3dkwn68sgb6htzc5w7vnm0000gn/T/rdbfiles3806849363 --dbfilename orange.rdb
[stage-201] $ redis-cli CONFIG get dir
[stage-201] Sent bytes: "*3\r\n$6\r\nCONFIG\r\n$3\r\nget\r\n$3\r\ndir\r\n"
[stage-201] Received bytes: "*2\r\n$3\r\ndir\r\n$75\r\n/private/var/folders/5l/z5y3dkwn68sgb6htzc5w7vnm0000gn/T/rdbfiles3806849363\r\n"
[stage-201] Received RESP value: ["dir", "/private/var/folders/5l/z5y3dkwn68sgb6htzc5w7vnm0000gn/T/rdbfiles3806849363"]
[stage-201] Received ["dir", "/private/var/folders/5l/z5y3dkwn68sgb6htzc5w7vnm0000gn/T/rdbfiles3806849363"]
[stage-201] Test passed.
[stage-201] Terminating program
[stage-201] Error terminating program: 'program failed to exit in 2 seconds after receiving sigterm'

[stage-202] Running tests for Stage #2: RDB Read Key
[stage-202] Created RDB file with single key: "raspberry"
[stage-202] $ ./spawn_redis_server.sh --dir /private/var/folders/5l/z5y3dkwn68sgb6htzc5w7vnm0000gn/T/rdbfiles3889106641 --dbfilename blueberry.rdb
[stage-202] $ redis-cli KEYS *
[stage-202] Test passed.
[stage-202] Terminating program
[stage-202] Error terminating program: 'program failed to exit in 2 seconds after receiving sigterm'

[stage-203] Running tests for Stage #3: RDB String Value
[stage-203] Created RDB file with single key-value pair: strawberry="mango"
[stage-203] $ ./spawn_redis_server.sh --dir /private/var/folders/5l/z5y3dkwn68sgb6htzc5w7vnm0000gn/T/rdbfiles240005537 --dbfilename pear.rdb
[stage-203] $ redis-cli GET strawberry
[stage-203] Test passed.
[stage-203] Terminating program
[stage-203] Error terminating program: 'program failed to exit in 2 seconds after receiving sigterm'

[stage-204] Running tests for Stage #4: RDB Read Multiple Keys
[stage-204] Created RDB file with 3 keys: ["orange" "blueberry" "banana"]
[stage-204] $ ./spawn_redis_server.sh --dir /private/var/folders/5l/z5y3dkwn68sgb6htzc5w7vnm0000gn/T/rdbfiles1686486797 --dbfilename mango.rdb
[stage-204] $ redis-cli KEYS *
[stage-204] Test passed.
[stage-204] Terminating program
[stage-204] Error terminating program: 'program failed to exit in 2 seconds after receiving sigterm'

[stage-205] Running tests for Stage #5: RDB Read Multiple String Values
[stage-205] Created RDB file with key-value pairs: "pineapple"="grape", "strawberry"="blueberry", "mango"="pineapple", "banana"="orange"
[stage-205] $ ./spawn_redis_server.sh --dir /private/var/folders/5l/z5y3dkwn68sgb6htzc5w7vnm0000gn/T/rdbfiles226907104 --dbfilename pear.rdb
[stage-205] $ redis-cli GET pineapple
[stage-205] $ redis-cli GET strawberry
[stage-205] $ redis-cli GET mango
[stage-205] $ redis-cli GET banana
[stage-205] Test passed.
[stage-205] Terminating program
[stage-205] Error terminating program: 'program failed to exit in 2 seconds after receiving sigterm'

[stage-206] Running tests for Stage #6: RDB Read Value With Expiry
[stage-206] $ ./spawn_redis_server.sh --dir /private/var/folders/5l/z5y3dkwn68sgb6htzc5w7vnm0000gn/T/rdbfiles1307091170 --dbfilename strawberry.rdb
[stage-206] $ redis-cli GET strawberry
[stage-206] $ redis-cli GET orange
[stage-206] $ redis-cli GET apple
[stage-206] $ redis-cli GET mango
[stage-206] Test passed.
[stage-206] Terminating program
[stage-206] Error terminating program: 'program failed to exit in 2 seconds after receiving sigterm'
```

2024-05-01 20:31 UTC, ryan-gang commented on internal/rdb_file_creator.go
> -func NewRDBFileCreator(stageHarness *test_case_harness.TestCaseHarness) (*RDBFileCreator, error) {
Unused parameter.

2024-05-01 20:32 UTC, ryan-gang commented on internal/redis_executable/redis_executable.go
> +func NewRedisExecutable(stageHarness *test_case_harness.TestCaseHarness, customTeardownFuncs ...func()) *RedisExecutable {
I have attached the logs as a comment.

2024-05-01 23:40 UTC, rohitpaulk requested changes
-

2024-05-01 23:40 UTC, rohitpaulk commented on internal/stages_test.go
> +		"rdb_keys":                {regexp.MustCompile(`\[stage-11\] .*`)},
@ryan-gang can we restrict this a bit? Maybe only if the line also starts with `Received` or so? This essentially turns off the diffing for the whole of stage-11, which isn't ideal

2024-05-01 23:40 UTC, rohitpaulk commented on internal/redis_executable/redis_executable.go
> +func NewRedisExecutable(stageHarness *test_case_harness.TestCaseHarness, customTeardownFuncs ...func()) *RedisExecutable {
@ryan-gang why does this need to be passed in as a param? Can't the caller just call `stageHarness.RegisterTeardownFunc` directly after calling this? (Should achieve the same effect?). 

That way the caller even has control over whether their teardown function runs before or after the redis binary's teardown function (they can just register the teardown func before or after this call)

2024-05-01 23:40 UTC, rohitpaulk commented on internal/resp_assertions/string_array_assertion.go
> +	shouldSortBeforeComparison bool
```suggestion
	ShouldSortBeforeComparison bool
```

(If `ExpectedValue` is public, no reason for this to not be)

2024-05-01 23:40 UTC, rohitpaulk commented on internal/resp_assertions/string_array_assertion.go
> +			return fmt.Errorf("Expected element #%d to be %q, got %q", i+1, expectedValue, actualElement)
@ryan-gang won't this end up being confusing? We're trying to convey order but we aren't conveying that we sort before comparison. 



- Say the expected was `Alice`, `Bob` & `Carl`. 
- And the actual returned is `Diana`, `Bob`, `Carl`

The logs would say something like: 

- Received "Diana", "Bob", "Carl"
- Error, expected first element to be "Alice", got "Bob"

2024-05-01 23:40 UTC, rohitpaulk commented on internal/resp_assertions/string_array_assertion.go
> +			return fmt.Errorf("Expected element #%d to be %q, got %q", i+1, expectedValue, actualElement)
The kind of error messages you want to convey here are significantly different, could even make sense to have these be two separate assertions - maybe name this `UnorderedStringArrayAssertion`?

The error message for the unsorted comparison could be something like: 

> Value missing in returned array: "Alice"
> Incorrect value(s) found in returned array: "Diana"

Or, to be simple for now, just: 

> Expected ["Alice", "Bob", "Carl"] (in any order), got ["Diana", "Bob", "Carl"]

2024-05-01 23:40 UTC, rohitpaulk commented on internal/test_helpers/fixtures/rdb-read-value-with-expiry/pass
> +[33m[stage-8] [0m[94mclient: $ redis-cli CONFIG get dir[0m
@ryan-gang let's change this to `CONFIG GET` to match the redis docs?

2024-05-01 23:40 UTC, rohitpaulk commented on internal/test_rdb_read_key.go
> +	b := redis_executable.NewRedisExecutable(stageHarness, func() { RDBFileCreator.Cleanup() })
Added notes on this above, I understand that we can't use `defer` but you should just be able to call `RegisterTeardownFunc` directly instead to get the ordering you want.

2024-05-03 13:59 UTC, ryan-gang commented on internal/resp_assertions/string_array_assertion.go
> +			return fmt.Errorf("Expected element #%d to be %q, got %q", i+1, expectedValue, actualElement)
Broke the `StringArrayAssertion` into 2 variants, Ordered and Unordered. 
The ordered one has this type of logs.
```
[stage-204] Value missing in correct position (#1) of returned array: "banana"
[stage-204] Incorrect value found in returned array: "banana"
```

2024-05-03 16:27 UTC, rohitpaulk commented
(dismissing coz of the unordered comparison change we talked about)

2024-05-04 07:50 UTC, ryan-gang commented on internal/resp_assertions/string_array_assertion.go
> +			return fmt.Errorf("Expected element #%d to be %q, got %q", i+1, expectedValue, actualElement)
Updated.

2024-05-04 20:59 UTC, rohitpaulk commented on internal/resp_assertions/unordered_string_array_assertion.go
> +	sort.Strings(a.ExpectedValue)
@ryan-gang Will this mutate the slice passed in by a client? If so we should probably make a copy and sort that instead, this could introduce bugs that are pretty hard to track down

2024-05-04 21:07 UTC, rohitpaulk commented on internal/test_rdb_read_multiple_keys.go
> +		Assertion:                 resp_assertions.NewUnorderedStringArrayAssertion(keys),
👌 like how this turned out!

2024-05-04 21:08 UTC, rohitpaulk approved these changes

2024-05-06 06:52 UTC, merged