CC-1181: Add section-specific log prefixes to all stages
codecrafters-io/redis-tester pull request #157
Opened 2024-06-28 16:38 UTC by ryan-gang

This pull request adds section-specific log prefixes to all stages in order to dynamically set section-specific log prefixes. This improves the readability and organization of the logs.

2024-07-01 14:25 UTC, rohitpaulk commented on internal/test_repl_info_replica.go
> +		logger.UpdateSecondaryPrefix("handshake")
Hmm, if this runs in a goroutine, couldn't it end up overridding the same logger used outside the goroutine?

2024-07-01 14:25 UTC, rohitpaulk requested changes
Added q

2024-07-01 14:25 UTC, rohitpaulk commented on internal/test_repl_info_replica.go
> +		logger.UpdateSecondaryPrefix("handshake")
Question re-phrased - how do we prevent race conditions here?

2024-07-04 10:36 UTC, ryan-gang commented on internal/test_repl_info_replica.go
> +		master, err := instrumented_resp_connection.NewFromConn(quietLogger, conn, "master")
We can now pass the `quietLogger` directly to silence all callbacks.

2024-07-04 10:37 UTC, ryan-gang commented on internal/test_repl_info_replica.go
> +		master, err := instrumented_resp_connection.NewFromConn(quietLogger, conn, "master")
No need to update log context.

2024-07-04 12:18 UTC, rohitpaulk commented on internal/instrumented_resp_connection/instrumented_resp_connection.go
> +func defaultCallbacks(Logger *logger.Logger, logPrefix string) resp_connection.RespConnectionCallbacks {
```suggestion
func defaultCallbacks(logger *logger.Logger, logPrefix string) resp_connection.RespConnectionCallbacks {
```

(havent' seen us naming variables with capitals elsewhere)

2024-07-04 12:20 UTC, rohitpaulk commented on internal/instrumented_resp_connection/instrumented_resp_connection.go
> +func defaultCallbacks(Logger *logger.Logger, logPrefix string) resp_connection.RespConnectionCallbacks {
Oh, is this to avoid conflicts with the package? In that case, I'd just import the package as `tester_utils_logger` or something like that. With this naming scheme it isn't clear why the variable is named differently.

2024-07-04 12:21 UTC, rohitpaulk commented on internal/test_repl_info_replica.go
> +	logger.UpdateSecondaryPrefix("test")
What's the prior prefix for other logs? Other stages have `handshake`, but I don't see that here

2024-07-04 12:23 UTC, rohitpaulk commented on internal/test_repl_master_cmd_prop.go
> +			// Assertion: resp_assertions.NewStringAssertion("OK"),
Stray comment

2024-07-04 12:25 UTC, rohitpaulk approved these changes

2024-07-06 09:17 UTC, merged