CC-1357: refactor logger.Infof calls for xread block tests
codecrafters-io/redis-tester pull request #161
Opened 2024-08-08 07:58 UTC by ryan-gang

This pull request refactors the logger.Infof calls in the xread block tests to use formatted strings. This improves code readability and maintainability.

2024-08-08 14:12 UTC, rohitpaulk commented on internal/test_helpers/fixtures/streams/pass
> +[33m[stage-44] [0m[94m$ redis-cli xread block 0 streams "pear 0-1"[0m
@ryan-gang can you check and see if "pear 0-1" is supposed to be quoted? I don't think it is: 

<img width="426" alt="Screenshot 2024-08-08 at 15 12 20" src="https://github.com/user-attachments/assets/f8320c52-16df-4f86-885c-c9d2d70b6bc9">

2024-08-08 14:13 UTC, rohitpaulk requested changes
Added note re: quoting

2024-08-08 17:54 UTC, ryan-gang commented on internal/test_helpers/fixtures/streams/pass
> +[33m[stage-44] [0m[94m$ redis-cli xread block 0 streams "pear 0-1"[0m
Yep, shouldn't be quoted as per docs. 
But, as there is spacing inside, we kept it like this. Should I remove this then ?
This works with redis either way.

2024-08-10 22:36 UTC, rohitpaulk commented on internal/test_helpers/fixtures/streams/pass
> +[33m[stage-44] [0m[94m$ redis-cli xread block 0 streams "pear 0-1"[0m
Yep let's remove quoting - seems like redis might have some kind of special handling for this if it works with quotes? The arguments seem to be separate arguments (one for key, one for id)

2024-08-19 08:23 UTC, ryan-gang commented
We use all unquoted params for `XREAD`, as per https://redis.io/docs/latest/commands/xread/.

2024-08-19 08:31 UTC, ryan-gang commented
Merging this in @rohitpaulk.

2024-08-19 08:32 UTC, merged