CC-1063: Update test to match stage description.
codecrafters-io/redis-tester pull request #94
Opened 2024-03-05 17:05 UTC by ryan-gang

2024-03-05 18:48 UTC, rohitpaulk requested changes
(comments added)

2024-03-05 18:48 UTC, rohitpaulk commented on internal/test_repl_replica_getack_nonzero.go
> +	err = master.GetAck(offset) // 37
@ryan-gang how come the values in the comments above (line 48) and below (line 64) is also `37`?

2024-03-06 06:34 UTC, ryan-gang commented on internal/test_repl_replica_getack_nonzero.go
> +	err = master.GetAck(offset) // 37
These are the byte offsets for the given command. Not the cumulative offset value. These were useful during writing the initial tests.
Should I remove these comments altogether ?

2024-03-06 11:16 UTC, rohitpaulk commented on internal/test_repl_replica_getack_nonzero.go
> +	err = master.GetAck(offset) // 37
Aha, no it's okay then

2024-03-06 11:16 UTC, rohitpaulk approved these changes

2024-03-07 07:08 UTC, qwertzguy commented
This technically still doesn't match the test description as the description mentions only sending one SET command but the test sends 2 of them.

2024-03-11 07:01 UTC, ryan-gang commented
We want 2 set of `SET` commands, it makes the tests more robust. Will update the description to mention the same.

2024-03-11 07:02 UTC, merged